---
title: "Process ReadVarsESO csv"
author: "Noah Klammer"
date: "3/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import

```{r import, message=FALSE, warning=FALSE}
library(readr)
eplusout <- read_csv("eplusout.csv")
# View(eplusout)
```


```{r include=FALSE}
# readr::spec(eplusout)

freq <- "null"
rows <- nrow(eplusout) 
if (rows==8760*4) {
  freq <- "15 minutes"
} else if (rows==8760) {
  freq <- "hourly"
} else if (rows==12) {
  freq <- "monthly"
} else {freq <- "could not determine"}

```
There are ``r ncol(eplusout)`` column variables in this file with names like ``r names(eplusout)[3]``, ``r names(eplusout)[50]``, and ``r names(eplusout)[100]``.

The frequency of this .eso file's timestep is ``r freq``.


### Get all var names that match "Sensible" && "Zone Ideal Loads"
```{r}
list <- grep('Sensible', value = TRUE,
  grep('Zone Ideal Loads', names(eplusout), value = TRUE) 
  )
# list
```

*Done*


### TODO - sort and fix "10" < "2"
```{r}
stringr::str_sort(list, numeric = TRUE)

# intialize array
index_df <- 0
for (i in 1:length(obj)) {
  index_df[i] <- substr(list[i], start = obj[i], stop = obj[i]+mlen[i]-1)
}
df <- rbind(as.numeric(index_df),list)
```


<br><br><br>